### ISSUE TITLE
Add iOS 14.x (14.3 is the most needed) Firmware Bundles

### ISSUE THREAD

**Issue by Grandboy46** [m1stadev/Inferius#26]
Due to incompatible SEP and Baseband, most of the firmware bundles for A9, A10, A11 are useless. We need ios 14 firmware bundles. It’s hard to create your own firmware bundle as well.

**Comment by Grandboy46** [comment]
iPhone 9,4 and 10,6 is what I need.

**Comment by m1stadev** [comment]
I'll take a look at creating some. As for creating your own firmware bundles, I'm working on a script to create them, so that should make the process a lot easier. I haven't tested iOS 14 custom restores though, so i'll need to do that as well.

**Comment by m1stadev** [comment]
Update: pushed the [script](https://github.com/m1stadev/Inferius/blob/rewrite/bundlegen).
