### ISSUE TITLE
Failed restore

### ISSUE THREAD

**Issue by tolikes** [m1stadev/Inferius#28]
./inferius -d iPhone9,1 -i 12.4 -f iPhone_4.7_P3_12.4_16G77_Restore_custom.ipsw -r
verifying version
extracting restore.plist
extracting buildmanifest.plist
[ERROR] This FutureRestore cannot be used with Inferius. Exiting...

**Comment by m1stadev** [comment]
As per the README, you need to use a build of futurerestore that has been compiled with my fork of img4tool. Also, an iPhone 7 downgrade to 12.4 won't work anyways.
