### ISSUE TITLE
FutureRestore NOT Installed!

### ISSUE THREAD

**Issue by Visualwit** [m1stadev/Inferius#29]
I Am Using The Rewrite Version On Inferius But I Am Using iPhone SE 1st Generation And I'm Downgrading To iOS 13.5 But Typing The Command In Terminal It Says: [ERROR] FutureRestore is not installed on your system. Exiting... Please Help Me!

**Comment by Visualwit** [comment]
ANYONE?

**Comment by tolikes** [comment]
Maybe this project abandoned

**Comment by m1stadev** [comment]
read the [README](https://github.com/m1stadev/Inferius) for the required dependencies.

**Comment by Visualwit** [comment]
I Don't Know How To Fully Install It!

**Comment by maximnait2000** [comment]
me too

**Comment by maximnait2000** [comment]
i think libzip  cant install on 11.13
