### ISSUE TITLE
[ERROR] Device did not enter recovery mode successfully!

### ISSUE THREAD

**Issue by Tgm77** [m1stadev/Inferius#30]
I have entered pwned dfu mode with signature checks removed but I still get this error:

[ERROR] Device did not enter recovery mode successfully! Make sure your device is in Pwned DFU mode with signature checks removed, then run this script again.
Exiting...

**Comment by m1stadev** [comment]
What device are you using, and what iOS version are you attempting to downgrade to?

**Comment by Tgm77** [comment]
I'm using an iPhone 5s (iPhone5,1) and attempting to downgrade to iOS 11.4.1
I have been using ipwndfu_public and running the command "python rmsigchks.py" to remove the signing checks.
I've double checked that the phone is pwndfu and I keep getting that same error.

**Comment by m1stadev** [comment]
Try pwning + patching signature checks with [iPwnder32](https://github.com/dora2-iOS/iPwnder32) perhaps? I've had issues with the signature check patches from Linus's ipwndfu fork in the past.

**Comment by Tgm77** [comment]
Sorry to ask, but I have a couple questions. First, how do I remove the signing checks with iPwnder32? Do I use the "--nibss" command or the "-f <img>" command. Second, what is the difference between pwnedibss and pwndfu mode? Finally, are kdfu mode and pwned dfu mode the same thing? I'm a huge noob with this kind of stuff as I'm only 12 and only have a year and a half of jailbreaking and downgrading experience.

**Comment by Tgm77** [comment]
Nvm. I figured everything out. I restored my iPhone and everything works. Btw, I'm the kid from discord who asked about futurerestore.
