### ISSUE TITLE
Re-add linux support

### ISSUE THREAD

**Issue by theIdeviceguy18383** [m1stadev/Inferius#31]
i used to be able to run this on linux but now it only supports macOS, what happened to linux support? can you try to add it back?

**Comment by m1stadev** [comment]
Linux support hasn't been removed, what error are you getting?

**Comment by theIdeviceguy18383** [comment]
it gives me this error
Traceback (most recent call last):
  File "./inferius.1", line 3, in <module>
    from utils.api import API
ModuleNotFoundError: No module named 'utils.api'
and according to the reade it says it requires a computer running macos

**Comment by m1stadev** [comment]
Can you re-clone the latest commit, and try again from within the Inferius directory?

**Comment by theIdeviceguy18383** [comment]
it is still the same

**Comment by m1stadev** [comment]
You don't seem to be running Inferius correctly. I've tested on a Linux machine on my end, and it works fine. As for the bundlegen script, it is macOS only, and that won't be changing any time soon.
