### ISSUE TITLE
[ERROR] This futurerestore cannot be used with Inferius. Exiting.

### ISSUE THREAD

**Issue by sandbox404** [m1stadev/Inferius#32]
hello, I compiled or installed all dependencies correctly (include your fork of img4tool), but it still says
[ERROR] This futurerestore cannot be used with Inferius. Exiting.

the out put of futurerestore: 
Version: e6c21f160eae23f9fab240fa088b0dcffca0e6b2 - 196
img4tool version: 0.199-c150c278bd9316a95d215363c2f3e998dede90ed-m1sta-RELEASE
libipatcher version: 0.82-0b2f79ff0917ef9b8a92475d93d9466b23fc2322-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes

I really need Inferius, what should I do next?
thx

**Comment by m1stadev** [comment]
Inferius verifies futurerestore by checking img4tool's version and making sure it's suffix-ed with `-m1sta`, but I didn't anticipate that there'd be other things suffixed to the end.

**Comment by D0lcegabbana** [comment]
> здравствуйте, я правильно скомпилировал или установил все зависимости (включая ваш форк img4tool), но там все еще написано[ОШИБКА] Это будущее восстановление не может быть использовано с Inferius. Выход.
> 
> выход из futurerestore:Версия: e6c21f160eae23f9fab240fa088b0dcffca0e6b2 - 196Версия img4tool: 0.199-c150c278bd9316a95d215363c2f3e998dede90ed-m1sta-RELEASEВерсия libipatcher: 0.82-0b2f79ff0917ef9b8a92475d93d9466b23fc2322-RELEASEOdysseus для 32-битной поддержки: даOdysseus для 64-разрядной поддержки: да
> 
> Мне действительно нужен Inferius, что мне делать дальше?спасибо

hello have you got the problem?
i faced similar problem.
but can't figure out how to compile futurerestore and img4tool correctly.
I also found a compiled futurerestore specifically for inferius, but I don’t know in which folder to insert it.
