### ISSUE TITLE
[Error] Asr64_patcher was not found on your system. Exiting.

### ISSUE THREAD

**Issue by arandomusernam** [m1stadev/Inferius#40]
Whenever I try to run bundlegen, I always get this error: /bundlegen -d iPhone9,4 -i 11.4.1
[ERROR] 'asr64_patcher' was not found on your system. Exiting. I have downloaded asr64_patcher and put it into the root directory, but I always get this error. Any help would be appreciated.

**Comment by vadimszzz** [comment]
Which root directory lol?

**Comment by vadimszzz** [comment]
You must put it into `/usr/local/bin`
Issue closed

**Comment by arandomusernam** [comment]
Thank you so much! This fixed it!
