### ISSUE TITLE
How to get a working futurerestore

### ISSUE THREAD

**Issue by arandomusernam** [m1stadev/Inferius#41]
This probably seems like a stupid question, but how should I compile futurerestore with M1stadev's fork of img4tool? I have tried downloading the latest compiled version of futurerestore from M1stadev's Github page, and Inferius just tells me that that futurerestore cannot be used with Inferius. Any help would be greatly appreciated!

**Comment by vadimszzz** [comment]
Download my Inferius, it works

**Comment by vadimszzz** [comment]
https://github.com/vadimszzz/Inferius

**Comment by arandomusernam** [comment]
Thanks so much! I will try this, and open reopen this issue or create a new one if it doesn't work. :)

Have a great day!

**Comment by adog9712** [comment]
@vadimszzz The futurerestore in your version of Inferius doesn't work. It still give the error that it can't be used with Inferius.
