### ISSUE TITLE
futurerestore 198 failed build

### ISSUE THREAD

**Issue by tolikes** [m1stadev/Inferius#47]
Making all in futurerestore
make[2]: *** No rule to make target `../external/idevicerestore/src/libidevicerestore.la', needed by `futurerestore'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by m1stadev** [comment]
This is not an Inferius issue.

**Comment by tolikes** [comment]
Yeah, but infernus requires the special futurerestore and after build does not recognize
